export const neighborhoods = [
  { name: 'Bairro Imperial de São Cristóvão', zone: 'Zona Central' },
  { name: 'Benfica', zone: 'Zona Central' },
  { name: 'Caju', zone: 'Zona Central' },
  { name: 'Catumbi', zone: 'Zona Central' },
  { name: 'Centro', zone: 'Zona Central' },
  { name: 'Cidade Nova', zone: 'Zona Central' },
  { name: 'Estácio', zone: 'Zona Central' },
  { name: 'Gamboa', zone: 'Zona Central' },
  { name: 'Glória', zone: 'Zona Central' },
  { name: 'Lapa', zone: 'Zona Central' },
  { name: 'Mangueira', zone: 'Zona Central' },
  { name: 'Paquetá', zone: 'Zona Central' },
  { name: 'Rio Comprido', zone: 'Zona Central' },
  { name: 'Santa Teresa', zone: 'Zona Central' },
  { name: 'Santo Cristo', zone: 'Zona Central' },
  { name: 'Saúde', zone: 'Zona Central' },
  { name: 'Vasco da Gama', zone: 'Zona Central' },
  { name: 'Botafogo', zone: 'Zona Sul' },
  { name: 'Catete', zone: 'Zona Sul' },
  { name: 'Copacabana', zone: 'Zona Sul' },
  { name: 'Cosme Velho', zone: 'Zona Sul' },
  { name: 'Flamengo', zone: 'Zona Sul' },
  { name: 'Gávea', zone: 'Zona Sul' },
  { name: 'Humaitá', zone: 'Zona Sul' },
  { name: 'Ipanema', zone: 'Zona Sul' },
  { name: 'Jardim Botânico', zone: 'Zona Sul' },
  { name: 'Lagoa', zone: 'Zona Sul' },
  { name: 'Laranjeiras', zone: 'Zona Sul' },
  { name: 'Leblon', zone: 'Zona Sul' },
  { name: 'Leme', zone: 'Zona Sul' },
  { name: 'Rocinha', zone: 'Zona Sul' },
  { name: 'São Conrado', zone: 'Zona Sul' },
  { name: 'Urca', zone: 'Zona Sul' },
  { name: 'Vidigal', zone: 'Zona Sul' },
  { name: 'Anil', zone: 'Zona Oeste' },
  { name: 'Barra da Tijuca', zone: 'Zona Oeste' },
  { name: 'Camorim', zone: 'Zona Oeste' },
  { name: 'Cidade de Deus', zone: 'Zona Oeste' },
  { name: 'Curicica', zone: 'Zona Oeste' },
  { name: 'Freguesia de Jacarepaguá', zone: 'Zona Oeste' },
  { name: 'Gardênia Azul', zone: 'Zona Oeste' },
  { name: 'Grumari', zone: 'Zona Oeste' },
  { name: 'Itanhangá', zone: 'Zona Oeste' },
  { name: 'Jacarepaguá', zone: 'Zona Oeste' },
  { name: 'Joá', zone: 'Zona Oeste' },
  { name: 'Praça Seca', zone: 'Zona Oeste' },
  { name: 'Pechincha', zone: 'Zona Oeste' },
  { name: 'Recreio dos Bandeirantes', zone: 'Zona Oeste' },
  { name: 'Tanque', zone: 'Zona Oeste' },
  { name: 'Taquara', zone: 'Zona Oeste' },
  { name: 'Vargem Grande', zone: 'Zona Oeste' },
  { name: 'Vargem Pequena', zone: 'Zona Oeste' },
  { name: 'Vila Valqueire', zone: 'Zona Oeste' },
  { name: 'Bangu', zone: 'Zona Oeste' },
  { name: 'Deodoro', zone: 'Zona Oeste' },
  { name: 'Gericinó', zone: 'Zona Oeste' },
  { name: 'Jardim Sulacap', zone: 'Zona Oeste' },
  { name: 'Magalhães Bastos', zone: 'Zona Oeste' },
  { name: 'Padre Miguel', zone: 'Zona Oeste' },
  { name: 'Realengo', zone: 'Zona Oeste' },
  { name: 'Santíssimo', zone: 'Zona Oeste' },
  { name: 'Senador Camará', zone: 'Zona Oeste' },
  { name: 'Vila Kennedy', zone: 'Zona Oeste' },
  { name: 'Vila Militar', zone: 'Zona Oeste' },
  { name: 'Barra de Guaratiba', zone: 'Zona Oeste' },
  { name: 'Campo Grande', zone: 'Zona Oeste' },
  { name: 'Cosmos', zone: 'Zona Oeste' },
  { name: 'Guaratiba', zone: 'Zona Oeste' },
  { name: 'Inhoaíba', zone: 'Zona Oeste' },
  { name: 'Paciência', zone: 'Zona Oeste' },
  { name: 'Pedra de Guaratiba', zone: 'Zona Oeste' },
  { name: 'Santa Cruz', zone: 'Zona Oeste' },
  { name: 'Senador Vasconcelos', zone: 'Zona Oeste' },
  { name: 'Sepetiba', zone: 'Zona Oeste' },
  { name: 'Alto da Boa Vista', zone: 'Zona Norte' },
  { name: 'Andaraí', zone: 'Zona Norte' },
  { name: 'Grajaú', zone: 'Zona Norte' },
  { name: 'Maracanã', zone: 'Zona Norte' },
  { name: 'Praça da Bandeira', zone: 'Zona Norte' },
  { name: 'Tijuca', zone: 'Zona Norte' },
  { name: 'Vila Isabel', zone: 'Zona Norte' },
  { name: 'Abolição', zone: 'Zona Norte' },
  { name: 'Água Santa', zone: 'Zona Norte' },
  { name: 'Cachambi', zone: 'Zona Norte' },
  { name: 'Del Castilho', zone: 'Zona Norte' },
  { name: 'Encantado', zone: 'Zona Norte' },
  { name: 'Engenho de Dentro', zone: 'Zona Norte' },
  { name: 'Engenho Novo', zone: 'Zona Norte' },
  { name: 'Higienópolis', zone: 'Zona Norte' },
  { name: 'Jacaré', zone: 'Zona Norte' },
  { name: 'Jacarezinho', zone: 'Zona Norte' },
  { name: 'Lins de Vasconcelos', zone: 'Zona Norte' },
  { name: 'Manguinhos', zone: 'Zona Norte' },
  { name: 'Maria da Graça', zone: 'Zona Norte' },
  { name: 'Méier', zone: 'Zona Norte' },
  { name: 'Piedade', zone: 'Zona Norte' },
  { name: 'Pilares', zone: 'Zona Norte' },
  { name: 'Riachuelo', zone: 'Zona Norte' },
  { name: 'Rocha', zone: 'Zona Norte' },
  { name: 'Sampaio', zone: 'Zona Norte' },
  { name: 'São Francisco Xavier', zone: 'Zona Norte' },
  { name: 'Todos os Santos', zone: 'Zona Norte' },
  { name: 'Bonsucesso', zone: 'Zona Norte' },
  { name: 'Bancários', zone: 'Zona Norte' },
  { name: 'Cacuia', zone: 'Zona Norte' },
  { name: 'Cidade Universitária', zone: 'Zona Norte' },
  { name: 'Cocotá', zone: 'Zona Norte' },
  { name: 'Freguesia', zone: 'Zona Norte' },
  { name: 'Galeão', zone: 'Zona Norte' },
  { name: 'Jardim Carioca', zone: 'Zona Norte' },
  { name: 'Jardim Guanabara', zone: 'Zona Norte' },
  { name: 'Maré', zone: 'Zona Norte' },
  { name: 'Moneró', zone: 'Zona Norte' },
  { name: 'Olaria', zone: 'Zona Norte' },
  { name: 'Pitangueiras', zone: 'Zona Norte' },
  { name: 'Portuguesa', zone: 'Zona Norte' },
  { name: 'Praia da Bandeira', zone: 'Zona Norte' },
  { name: 'Ramos', zone: 'Zona Norte' },
  { name: 'Ribeira', zone: 'Zona Norte' },
  { name: 'Tauá', zone: 'Zona Norte' },
  { name: 'Zumbi', zone: 'Zona Norte' },
  { name: 'Acari', zone: 'Zona Norte' },
  { name: 'Anchieta', zone: 'Zona Norte' },
  { name: 'Barros Filho', zone: 'Zona Norte' },
  { name: 'Bento Ribeiro', zone: 'Zona Norte' },
  { name: 'Brás de Pina', zone: 'Zona Norte' },
  { name: 'Campinho', zone: 'Zona Norte' },
  { name: 'Cavalcanti', zone: 'Zona Norte' },
  { name: 'Cascadura', zone: 'Zona Norte' },
  { name: 'Coelho Neto', zone: 'Zona Norte' },
  { name: 'Colégio', zone: 'Zona Norte' },
  { name: 'Complexo do Alemão', zone: 'Zona Norte' },
  { name: 'Cordovil', zone: 'Zona Norte' },
  { name: 'Costa Barros', zone: 'Zona Norte' },
  { name: 'Engenheiro Leal', zone: 'Zona Norte' },
  { name: 'Engenho da Rainha', zone: 'Zona Norte' },
  { name: 'Guadalupe', zone: 'Zona Norte' },
  { name: 'Honório Gurgel', zone: 'Zona Norte' },
  { name: 'Inhaúma', zone: 'Zona Norte' },
  { name: 'Irajá', zone: 'Zona Norte' },
  { name: 'Jardim América', zone: 'Zona Norte' },
  { name: 'Madureira', zone: 'Zona Norte' },
  { name: 'Marechal Hermes', zone: 'Zona Norte' },
  { name: 'Oswaldo Cruz', zone: 'Zona Norte' },
  { name: 'Parada de Lucas', zone: 'Zona Norte' },
  { name: 'Parque Anchieta', zone: 'Zona Norte' },
  { name: 'Parque Colúmbia', zone: 'Zona Norte' },
  { name: 'Pavuna', zone: 'Zona Norte' },
  { name: 'Penha', zone: 'Zona Norte' },
  { name: 'Penha Circular', zone: 'Zona Norte' },
  { name: 'Quintino Bocaiuva', zone: 'Zona Norte' },
  { name: 'Ricardo de Albuquerque', zone: 'Zona Norte' },
  { name: 'Rocha Miranda', zone: 'Zona Norte' },
  { name: 'Tomás Coelho', zone: 'Zona Norte' },
  { name: 'Turiaçu', zone: 'Zona Norte' },
  { name: 'Vaz Lobo', zone: 'Zona Norte' },
  { name: 'Vicente de Carvalho', zone: 'Zona Norte' },
  { name: 'Vigário Geral', zone: 'Zona Norte' },
  { name: 'Vila da Penha', zone: 'Zona Norte' },
  { name: 'Vila Kosmos', zone: 'Zona Norte' },
  { name: 'Vista Alegre', zone: 'Zona Norte' },
];
